### PR TITLE
Ported to babel 6

### PR DESCRIPTION
**Pull request by mutac**
Hi,

Thanks code.  A repo is worth 1,000 words.  I wanted to use babel 6, so I committed a port.

Thanks,
_matt

### CODE REVIEW

**Comment by developit** [comment]
Cool - @mutac do you mind if I merge this to a branch for now?
Babel 6 is still pretty new and is still missing support for some features like Decorators and loose mode.

**Comment by developit** [comment]
@mutac this is now merged into the `babel-6` branch, and released to npm as `1.0.0-alpha2`.

**Comment by developit** [comment]
(I'm closing this since it's merged, just not to `master`)

**Comment by mutac** [comment]
Cool, thank you!

**Pull request closed without merging**
